name: ci-run
on: 
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: "checkout-code"
        uses: actions/checkout@v2

      - name: "set node version" 
        uses: actions/setup-node@v2
        with:
          node-version: "15.14.0"
      
      - name: "install dependencies"
        run: "npm i --prefix ./codebase/rdicidr-0.1.0"