on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - 'releases/**'

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2